#cloud-config
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - git

# apt-get update, instantiate production TIG stack pinned to stable versions as of 7/13/2021
runcmd:
  - apt-get update -y
  - chown -R ubuntu:ubuntu /home/ubuntu
  - bash /home/ubuntu/tig.sh
  
# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /home/ubuntu/irssi.sh
    permissions: '0755'
    owner: ubuntu:ubuntu
    content: |
      sudo apt update ; sudo apt install -y build-essential net-tools
      # This shell script is just for reference to ensure it works outside of the cloud-init process and so it can be formatted into the cloudinit.yml
      sudo apt update ; sudo apt install -y build-essential net-tools software-properties-common irssi irssi-scripts screen openssh-server oidentd jq
      sudo systemctl enable --now oidentd

      # Retrieve irssi CONFIG from Github Gist: 
      curl https://api.github.com/gists/${var.irssi_gist} |jq ".files.config.content | fromjson" |& tee config

      # create irc unprivileged user 
      sudo -i
      bash /home/ubuntu/users.sh ${var.irc_username} ${var.gh_username}

      # Retrieve irssi CONFIG from Github Gist: 
      curl https://api.github.com/gists/${var.irssi_gist} |jq ".files.config.content | fromjson" |& tee /home/${irc_username}/.irssi/config
      chown -r ${var.irc_username}:${var.irc_username}/home/${irc_username}/.irssi/
  - path: /home/ubuntu/users.sh
    permissions: '0755'
    owner: ubuntu:ubuntu
    content: |
      #!/bin/bash

      USERNAME="$1"
      GITHUB="$2"
      #!/bin/bash

      USERNAME="$1"
      GITHUB="$2"
      PASSWORD="*"

      display_usage() {
        echo "This script must be run as root."
        echo -e "\nUsage: $0 Username GitHub \n"
      }

      # if more/less than two arguments supplied, display usage
      if [  $# -ne 2 ]; then
        display_usage
        exit 1
      fi

      # if not root, exit
      if [ $(whoami) != 'root' ]; then
        echo "Must be root to run $0"
        exit 1;
      fi

      if id -u "$USERNAME" >/dev/null 2>&1; then
        userdel -r -f $USERNAME
        useradd -m -p $PASSWORD -s /bin/bash $USERNAME
        echo $USERNAME:$PASSWORD | chpasswd
        mkdir /home/$USERNAME/.ssh && chown $USERNAME:$USERNAME /home/$USERNAME/.ssh
        sudo -i -u $USERNAME bash << EOF
        ssh-import-id-gh $GITHUB
      EOF

      else
      useradd -m -p $PASSWORD -s /bin/bash $USERNAME
      echo $USERNAME:$PASSWORD | chpasswd
      mkdir /home/$USERNAME/.ssh && chown $USERNAME:$USERNAME /home/$USERNAME/.ssh
      sudo -i -u $USERNAME bash << EOF
        ssh-import-id-gh $GITHUB
      EOF
      fi